---
- hosts: all
  become: yes
  tasks:
    - name: Remove aws cli
      file:
        path: /usr/local/aws-cli
        state: absent

    - name: Remove AWS CLI executable link
      file:
        path: /usr/local/bin/aws
        state: absent

    - name: Get list of all Docker images
      command: docker images -q
      register: docker_images
      changed_when: false
      ignore_errors: yes

    - name: Remove all docker images
      command: docker rmi -f {{ item }}
      with_items: "{{ docker_images.stdout_lines }}"
      when: docker_images.stdout_lines | length > 0

    - name: Remove the docker
      package:
        name: docker
        state: absent
    
    - name: Remove docker binaries
      file:
        path: /usr/bin/docker
        state: absent
    - name: Remove .aws cred folder
      file:
        path: /root/.aws
        state: absent

    - name: Remove Docker directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/docker
        - /etc/docker
        - /var/run/docker.sock
        
    - name: Remove Docker GPG key
      command: rm /etc/apt/keyrings/docker.gpg
      ignore_errors: true

    - name: Remove Docker repository list file
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent
      ignore_errors: true

    - name: Cleanup apt cache
      apt:
        update_cache: yes
        autoclean: yes
        autoremove: yes
    
    - name: Remove Directory
      file:
        path: /home/ubuntu/s3-data
        state: absent

      
